package softwaretest.dao;

import softwaretest.entity.LoginInfo;

public interface LoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    int insert(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    int insertSelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    LoginInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    int updateByPrimaryKeySelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    int updateByPrimaryKey(LoginInfo record);
}