package softwaretest.entity;

public class LoginInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.id
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.user_id
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_info.login_time
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    private String loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.id
     *
     * @return the value of login_info.id
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.id
     *
     * @param id the value for login_info.id
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.user_id
     *
     * @return the value of login_info.user_id
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.user_id
     *
     * @param userId the value for login_info.user_id
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_info.login_time
     *
     * @return the value of login_info.login_time
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_info.login_time
     *
     * @param loginTime the value for login_info.login_time
     *
     * @mbg.generated Fri Sep 06 23:13:41 CST 2019
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }
}